### PR TITLE
Cuda api9.0

### PR DESCRIPTION
**Pull request by yanghaku**
In order to adapt to the current experimental environment, the current branch is modified to a version suitable for ubuntu18.04, qemu 2.12.1 cuda 9.0.

### CODE REVIEW

**Comment by coldfunction** [comment]
Thank you very much for this PR. It has been three years since the last commit to this project. I’m very glad that you help to update the QEMU and CUDA versions. Although now I don’t have any GPU at hand, I will try my best to conduct a GPU test environment or ask the other contributors who can give a review.

By the way, it would be better if you can provide us with the information on the testing hardware, especially the GPU device.

Many thanks.

**Comment by yanghaku** [comment]
## hardware information

* GPU: GeForce GTX 1050Ti
* CPU: AMD Ryzen 7 3700X 8-Core Processor

## environment

* host OS: Linux ubuntu 5.4.0-65-generic # 73~18.04.1-Ubuntu SMP Tue Jan 19 09:02:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Nvidia driver:   NVIDIA-SMI 460.39       Driver Version: 460.39       CUDA Version: 11.2
* CUDA tookit version: cuda 9.0
* NVCC: Cuda compilation tools, release 9.0, V9.0.176
* gcc version 5.5.0 20171010 (Ubuntu 5.5.0-12ubuntu1)
* guest OS: Linux ubuntu 4.15.0-136-generic # 140-Ubuntu SMP Thu Jan 28 05:20:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* QEMU emulator version 2.12.1

## my Test

### deviceQuery in guest OS

```shell
/home/guest/NVIDIA_CUDA-9.0_Samples/1_Utilities/deviceQuery/deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GeForce GTX 1050 Ti"
  CUDA Driver Version / Runtime Version          11.2 / 9.0
  CUDA Capability Major/Minor version number:    6.1
  Total amount of global memory:                 4032 MBytes (4227858432 bytes)
  ( 6) Multiprocessors, (128) CUDA Cores/MP:     768 CUDA Cores
  GPU Max Clock rate:                            1392 MHz (1.39 GHz)
  Memory Clock rate:                             3504 Mhz
  Memory Bus Width:                              128-bit
  L2 Cache Size:                                 1048576 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 38 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 11.2, CUDA Runtime Version = 9.0, NumDevs = 1
Result = PASS
```

### bandwidthTest in guest OS

```shell
[CUDA Bandwidth Test] - Starting...
Running on...

 Device 0: GeForce GTX 1050 Ti
 Quick Mode

 Host to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)	Bandwidth(MB/s)
   33554432			12691.4

 Device to Host Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)	Bandwidth(MB/s)
   33554432			13108.2

 Device to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)	Bandwidth(MB/s)
   33554432			94722.8

Result = PASS

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.
```

## additional

Thank you for your reply. I am updating the QEMU and CUDA versions to do a comparison experiment of GPU virtualization. For my follow-up experiments, I will continue to improve this branch, and thank the contributors for their good comments.

Thanks !!

**Comment by ginsongsong** [comment]
Hi @yanghaku , 

Why are you using the 18.04 to be your guest os? 
The native version for cuda 9 are using gcc5, it need to downgrade the gcc/g++ version to build the runtime and qcu-driver.

Is it possible to use the 16.04 instead of 18.04 to apply the guest os and host os?

**Comment by yanghaku** [comment]
> Hi @yanghaku ,
> 
> Why are you using the 18.04 to be your guest os?
> The native version for cuda 9 are using gcc5, it need to downgrade the gcc/g++ version to build the runtime and qcu-driver.
> 
> Is it possible to use the 16.04 instead of 18.04 to apply the guest os and host os?

Yes, if you use ubuntu18.04, you need to downgrade the gcc version. The experiment I am doing recently is to compare qcuda with native. I think I need to control the version of the operating system, and the kernel version is the same, so I also use the same system as the host (ubuntu18.04) in the guest OS.

ubuntu18.04 is my development environment. I think the guest OS uses ubunt16.04 as well, but the host OS uses ubuntu16.04 to build qemu-2.12.1 may be uncertain.

**Pull request merged**
